name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag robot_console_dev_image:latest
    - name: Stop and Remove Old Container
      run: |
        if (docker ps -q --filter "name=robot_console") {
            docker stop robot_console
            docker rm robot_console
        } else {
            Write-Output "No container to remove"
        }

    - name: Run Docker Container
      run: |
        docker run -d --name robot_console --restart always -p 8080:8081 robot_console_dev_image:latest
