name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy: # Đổi tên job cho rõ ràng hơn

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Deploy with Docker Compose
      run: docker-compose up -d --build